if(CMAKE_GENERATOR STREQUAL "Ninja")
	set(arch "")
	set(os "")
	if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
		set(os "mac")
	elseif(CMAKE_SYSTEM_NAME STREQUAL Windows)
		set(os "win")
		if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
			set(arch "aarch64")
		endif()
	elseif (CMAKE_SYSTEM_NAME STREQUAL Linux) 
		set(os "linux")
		if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
			set(arch "arm64")
		endif()
	endif()
	
	if(EXISTS ${CMAKE_SOURCE_DIR}/tools/ninja)
        message(STATUS "ninja compiler found")
    else()
		download_file(https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-${os}${arch}.zip ${CMAKE_SOURCE_DIR}/tools/ninja e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
	endif()
endif()