
set(ISPC_PATH "${CMAKE_SOURCE_DIR}/tools/ispc/bin")
IF(NOT EXISTS ${ISPC_PATH})
	set(ISPC_VERSION "v1.25.3")
	set(ISPC_DOWNLOAD_URL "")
	set(ISPC_OS "")
	set(ISPC_DOWNLOAD_TYPE "")
	if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
		set(ISPC_DOWNLOAD_TYPE "tar.gz")
		set(ISPC_OS "macOS.universal")
	elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
		set(ISPC_DOWNLOAD_TYPE "zip")
		set(ISPC_OS "windows")
	elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux") 
		set(ISPC_DOWNLOAD_TYPE "tar.gz")
		set(ISPC_OS "linux")
	endif()
	
	set(ISPC_DOWNLOAD_URL "https://github.com/ispc/ispc/releases/download/${ISPC_VERSION}/ispc-${ISPC_VERSION}-${ISPC_OS}.${ISPC_DOWNLOAD_TYPE}")
	message(STATUS "Download ispc from ${ISPC_DOWNLOAD_URL}")
	set(ISPC_DOWNLOAD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/tools")
	if(${ISPC_DOWNLOAD_URL} MATCHES "\\.tar\\.gz$")
		set(ISPC_FILE "ispc.tar.gz" )
		file(DOWNLOAD ${ISPC_DOWNLOAD_URL} ${ISPC_DOWNLOAD_DIR}/${ISPC_FILE} SHOW_PROGRESS)
   	 	execute_process(
        	COMMAND ${CMAKE_COMMAND} -E tar xzf ${ISPC_DOWNLOAD_DIR}/${ISPC_FILE} --strip-components=1
        	WORKING_DIRECTORY ${ISPC_DOWNLOAD_DIR})

	elseif(${ISPC_DOWNLOAD_URL} MATCHES "\\.zip$")
		set(ISPC_FILE "ispc.zip" )
		file(DOWNLOAD ${ISPC_DOWNLOAD_URL} ${ISPC_DOWNLOAD_DIR}/${ISPC_FILE} SHOW_PROGRESS)
    	execute_process(
        	COMMAND ${CMAKE_COMMAND} -E tar xzf ${ISPC_DOWNLOAD_DIR}/${ISPC_FILE}
        	WORKING_DIRECTORY ${ISPC_DOWNLOAD_DIR})
	else()
    	message(FATAL_ERROR "Unsupported archive format: ${ISPC_DOWNLOAD_URL}")
	endif()
	file(REMOVE ${ISPC_DOWNLOAD_DIR}/${ISPC_FILE})
	file(RENAME "${ISPC_DOWNLOAD_DIR}/ispc-${ISPC_VERSION}-${ISPC_OS}" ${ISPC_DOWNLOAD_DIR}/ispc)
endif()
